version: '3'
services:
  soranchu_api:
    container_name: soranchu_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
